### ISSUE TITLE
First time using `slimta-setup config` returns error

### ISSUE THREAD

**Issue by ajh123** [slimta/slimta#16]
When I used the `slimta-setup config` program the error was returned
```python
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\slimta-setup.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\slimta\app\setup.py", line 160, in setup
    _setup_configs(parser, args)
  File "C:\Python310\lib\site-packages\slimta\app\setup.py", line 59, in _setup_configs
    if os.getuid() != 0:
AttributeError: module 'os' has no attribute 'getuid'. Did you mean: 'getpid'?
```

Python `3.10.2` is being used on Windows 10. Using WSL Ubuntu it works fine.

**Comment by denini08** [comment]
Hi! I was browsing through the project issues and noticed this one about Windows compatibility. 

I went ahead and created this fix to help out. This fix solves the first problem described. 

Happy to contribute to the project!

Let me know if you need any changes or have feedback on the approach.
