### ISSUE TITLE
KeyError: 'key_template'

### ISSUE THREAD

**Issue by aristide** [slimta/slimta#4]
hi!! 
i just installed **slimta** on my LinuxMint17 distibution  **#pip install slimta**.
With `$slimta-setup config`  i got the default yaml setting file  **slimta.yml**.

But when a ran `$slimat --no-daemon` i got this error:

```
aristide@zirconium ~ $slimta --no-daemon
Traceback (most recent call last):
  File "/usr/local/bin/slimta", line 9, in <module>
    load_entry_point('slimta==0.4.3', 'console_scripts', 'slimta')()
  File "/usr/local/lib/python2.7/dist-packages/slimta/app/main.py", line 57, in main
    state.loop()
  File "/usr/local/lib/python2.7/dist-packages/slimta/app/state.py", line 515, in loop
    self.start_everything()
  File "/usr/local/lib/python2.7/dist-packages/slimta/app/state.py", line 510, in start_everything
    self._start_edge(name, options)
  File "/usr/local/lib/python2.7/dist-packages/slimta/app/state.py", line 448, in _start_edge
    kwargs['validator_class'] = build_smtpedge_validators(options)
  File "/usr/local/lib/python2.7/dist-packages/slimta/app/helpers.py", line 132, in build_smtpedge_validators
    rules = RuleHelpers(options)
  File "/usr/local/lib/python2.7/dist-packages/slimta/app/helpers.py", line 67, in __init__
    self.lookup_creds = load_lookup(rules.get('lookup_credentials'))
  File "/usr/local/lib/python2.7/dist-packages/slimta/app/lookup.py", line 75, in load_lookup
    return _load_dict_lookup(options)
  File "/usr/local/lib/python2.7/dist-packages/slimta/app/lookup.py", line 64, in _load_dict_lookup
    return DictLookup(options.map, options.key_template)
  File "/usr/local/lib/python2.7/dist-packages/slimta/app/config.py", line 47, in __getattr__
    return self[key]
KeyError: 'key_template'
```

I need help to correct this issue!!

**Comment by icgood** [comment]
Hey @aristide, apparently I forgot to test that very simple use-case when I was messing with that bit of code a few months ago. Thanks for reporting! I have uploaded a new version (0.4.4) to PyPi, so you should be able to update to the latest with `# pip install -U --no-deps slimta`.

**Comment by icgood** [comment]
Here was the change, for reference: 0daf11db1757c93200a2d04b5ceb8a6f74c81eef

**Comment by aristide** [comment]
great thanks @icgood. Now it's work :smile:
