### ISSUE TITLE
Error when using slimta-setup config

### ISSUE THREAD

**Issue by martmists** [slimta/slimta#5]
```
path/to/dir# slimta-setup config
Traceback (most recent call last):
  File "/usr/local/bin/slimta-setup", line 7, in <module>
    from slimta.app.setup import setup
  File "/usr/local/lib/python3.5/dist-packages/slimta/app/setup.py", line 69
    os.makedirs(etc_dir, 0755)
                            ^
SyntaxError: invalid token
```

**Comment by icgood** [comment]
@martmists I haven't put the time in yet to making this package compatible with Python 3.x, unfortunately. In the meantime, a [`virtualenv`](https://virtualenv.pypa.io/en/stable/) with Python 2.7  should work just fine:

Example:
```bash
virtualenv -p $(which python2) /opt/slimta
source /opt/slimta/bin/activate
```
