### ISSUE TITLE
Is it possible to run without TLS? 

### ISSUE THREAD

**Issue by mrPsycho** [slimta/slimta#7]
Hello,
just installed it and trying to start... but get this error:

    root@staff:# slimta --no-daemon -c slimta/slimta.yaml
    Traceback (most recent call last):
      File "/usr/local/bin/slimta", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python2.7/site-packages/slimta/app/main.py", line 57, in main
        state.loop()
      File "/usr/local/lib/python2.7/site-packages/slimta/app/state.py", line 529, in loop
        self.start_everything()
      File "/usr/local/lib/python2.7/site-packages/slimta/app/state.py", line 524, in start_everything
        self._start_edge(name, options)
      File "/usr/local/lib/python2.7/site-packages/slimta/app/state.py", line 468, in _start_edge
        new_edge = SmtpEdge(listener, queue, **kwargs)
    TypeError: __init__() got an unexpected keyword argument 'tls'

config:

    process:
      slimta:
        daemon: false
    edge:
      outbound:
        type: smtp
        queue: outbound
        listener:
          interface: '127.0.0.1'
          port: 25
    queue:
      outbound:
        type: memory
        relay: outbound
        policies:
          - { type: add_date_header }
          - { type: add_messageid_header }
          - { type: add_received_header }
          - { type: recipient_domain_split }
    relay:
      outbound:
        type: mx

how to start simple openrelay for localhost?

**Comment by icgood** [comment]
@mrPsycho thanks for the issue! I had been doing my testing against the `master` branch, which works as expected, but forgot to tag a new version that reflected my changes.

I have tagged version 0.6.0 and uploaded to [PyPI](https://pypi.python.org/pypi/slimta/0.6.0). If you run `pip install -U slimta`, your config should work properly.
